### ISSUE TITLE
Unable to get websocket connection 

### ISSUE THREAD

**Issue by avnsri4986** [Enterprise-connect/ec-sdk#10]
Unable to get a valid websocket connection. 
Process: 
- Create Enterprise Connect Service on Predix CF by <br/>**`cf cs enterprise-connect Beta avn-ecs-test -c "{\"trustedIssuerIds\":\"https://51f5859c-f50d-4d15-ac96-055da3bc038c.predix-uaa.run.aws-usw02-pr.ice.predix.io/oauth/token\", \"ec-info\":{\"whiteList\":[\"165.156.29.0/24\",\"3.209.204.0/24\"], \"blockList\":[]}}"`**
- Added Scope/Authority on UAA. 
- Deployed ECAgent in Gateway mode with the following scipt<br/> **`./ecagent_linux -mod "gateway" -lpt ${PORT} -zon "enterprise-connect-zone-id" -sst "enterprise-connect-service-url" -oa2 "uaa-url/oauth/token" -csc "secret" -cid "clientid" -wtl "0.0.0.0/0,165.156.29.0/24,3.209.204.0/24"`**
- Ran the following Command to obtain a server: <br/> **`ecagent_windows -oa2 "uaa-url/oauth/token" -hst "wss://ec-gateway.run.aws-usw02-pr.ice.predix.io" -csc "secret" -cid "clientid" -aid "191001" -pxy "proxy-url" -mod "server" -dur "7500" -rht "localhost" -rpt "5432"
`**
- Everytime I try to run this I get 

> websocket: bad handshake
![error_snippet](https://cloud.githubusercontent.com/assets/24874130/21600700/8d24aa70-d1a6-11e6-807e-b1e2f571fbda.png)

**Comment by palokam** [comment]
Avneesh, we will fix this ASAP

**Comment by avnsri4986** [comment]
@palokam, can we mark this as fixed since we no longer need to create gateways ourselves ?

**Comment by chiacchang** [comment]
the current ecagent gateway's experiment. Release in progress.

**Comment by chiacchang** [comment]
This issue does not persist in v1.2.70.
