### ISSUE TITLE
Remote Postgre Connections Receving Error after Binary: v1.60_fukuoka

### ISSUE THREAD

**Issue by avnsri4986** [Enterprise-connect/ec-sdk#11]
Can't use **v1.60_fukuoka** binaries to connect to postgre instances. I receive the following error: 

`client sent partial pkt in startup phase`

Meanwhile, it works perfectly in **v1.27_fukuoka**

**Comment by chiacchang** [comment]
Please try >=v1.64.

**Comment by chiacchang** [comment]
Issue does not persist in v1.2.70.
