### ISSUE TITLE
Auto Refresh Token issue on PREDIX SELECT Environment UAA - Write: broken pipe

### ISSUE THREAD

**Issue by palokam** [Enterprise-connect/ec-sdk#12]
Auto Refresh Token failing to get the token from https://UAA/oauth/token with an Error

write: broken pipe

**Comment by chiacchang** [comment]
in investigation.

**Comment by chiacchang** [comment]
issue cannot be reproduced. Please verify again with the current release. @palokam

**Comment by palokam** [comment]
ecagent_darwin does not work, but ecagent_windows and ecagent_linux works as well

**Comment by chiacchang** [comment]
a release-candidate has been rolled out. please help identify if it's a valid fix. https://github.com/Enterprise-connect/ec-sdk/releases/tag/v1.2.82

**Comment by palokam** [comment]
Just tested this morning, ecagent_darwin_sys/_var does not work on BASIC, but ecagent_linux_sys from Predix Devbox on my mac.

...Logs..

 [EC Client] 2017/01/15 08:44:58 v1.86_fukuoka
 [EC Client] 2017/01/15 08:44:58 refresh duration is specified. Token auto-refresh is set.
 [EC Client] 2017/01/15 08:44:58 Fetching new token..
 [EC Debug] 2017/01/15 08:44:58 url.URL=>{https  <nil> 0ec683ef-3579-4a8e-9c01-a6984b4d9ec3.predix-uaa.run.aws-usw02-pr.ice.predix.io /oauth/token  false  }
 [EC Client] 2017/01/15 08:45:08 Post https://0ec683ef-3579-4a8e-9c01-a6984b4d9ec3.predix-uaa.run.aws-usw02-pr.ice.predix.io/oauth/token: net/http: TLS handshake timeout
