### ISSUE TITLE
Predix East(SELECT) - handshake issue

### ISSUE THREAD

**Issue by palokam** [Enterprise-connect/ec-sdk#13]
could not establish the handshake with the gateway from on-premise to Predix East environment

**Comment by chiacchang** [comment]
Verifying.

**Comment by chiacchang** [comment]
Issue identified.. it's being caused by the ip filtering and a set of malformed ip addresses on the GE Predix East Env. Will roll out a patch soon in next release.

**Comment by chiacchang** [comment]
The issue has been fixed in v1.75 release. @palokam
