### ISSUE TITLE
ecagent need to read environment variables in any mode(server/client/gateway)

### ISSUE THREAD

**Issue by palokam** [Enterprise-connect/ec-sdk#16]
Set the environmental variables instead of invoking along the agent command line. This is a well established industry standard example postgres database use this technique to protect the password exposures in the command line. This can be done in a user started up bash as well.

example ec.sh shell script below

**Before:**
#!bin/bash
./ecagent_os -mod  Client|Server|Gateway ..etc

**After**
#!bin/bash
set/export ECAGENT-mod=Client|Server|Gateway
./ecagent_os

**Comment by chiacchang** [comment]
The repo has been opensourced to a maximum customisation. It can be compiled according to users' project need. For internal user, Please visit the repo to utilise the go libraries/pacakge.

https://github.build.ge.com/Enterprise-Connect/ec-agent-evolution
