### ISSUE TITLE
IP request information is not available in -dbg mode

### ISSUE THREAD

**Issue by palokam** [Enterprise-connect/ec-sdk#18]
Http 101 request is not captured in the debug logs. in ecagent, there is no way to know the IPs range  to include in the gateway.

Capture HTTP 101 request in debug mode or when there is a WebSocket bad handshake

**Comment by kyasuda2003** [comment]
In progress.

**Comment by chiacchang** [comment]
In progress.

**Comment by palokam** [comment]
fixed - thanks - @chiacchang
