### ISSUE TITLE
Add trustedissuerID to the EC service VCAP.

### ISSUE THREAD

**Issue by palokam** [Enterprise-connect/ec-sdk#19]
This will reduce people using 2 different UAA between EC agent and EC service.

**Comment by kyasuda2003** [comment]
In progress.

**Comment by chiacchang** [comment]
In progress.

**Comment by chiacchang** [comment]
Added in EC service instance.

**Comment by chiacchang** [comment]
@palokam please close it.

**Comment by palokam** [comment]
Thanks Chia, closed now
