### ISSUE TITLE
Adding -wht as default and required parameter - EC Gateway

### ISSUE THREAD

**Issue by palokam** [Enterprise-connect/ec-sdk#20]
Add whitelist as required and default value "0.0.0.0/0".

If you the EC gateway is deployed with default please log that in the gateway logs

**Comment by chiacchang** [comment]
The default is always populated with "0.0.0.0/0,::/0" for -wht. will log the value.

**Comment by palokam** [comment]
'x-forward-for' or equivalent header should have the information of the all IPs involved EC Agent in making the connection and should be all in the -wtl list

**Comment by chiacchang** [comment]
whitelist/block list are supported in current release. @palokam
