### ISSUE TITLE
Cannot Delete Service in CloudFoundry 

### ISSUE THREAD

**Issue by CypherZero** [Enterprise-connect/ec-sdk#21]
We've tried to delete unused EC services in our space, but was met with this error message: 
brianwong@C02QK08XG8WP ~/Source/CAS/CASCADE/Dev-Core (DE18956●)$ cf ds cascade-agent-gateway                                                                                                      [2.3.0]

Really delete the service cascade-agent-gateway?> y
Deleting service cascade-agent-gateway in org CASCADE_Select / space CASCADE-DEV as 212398339@mail.ad.ge.com...
FAILED
Server error, status code: 502, error code: 10001, message: Service instance cascade-agent-gateway: Service broker error: java.lang.NullPointerException

**Comment by chiacchang** [comment]
what's the zone id of this instance? (cf service <service_name> --guid) @CypherZero

**Comment by santoshsinha** [comment]
This issue is still there. Is this going to be resolved before GA.

**Comment by chiacchang** [comment]
The issue is handled by GE Digital Cloud Foundry operation.
