### ISSUE TITLE
EC Client - Server setup

### ISSUE THREAD

**Issue by vishalrmakwana** [Enterprise-connect/ec-sdk#23]
My requirement is to access Postgre in predix from my local ( jdbc)
I have EC gateway and EC server installed in predix environment and I start client on my windows machine. 
When I call my postgre DB (as mentioned in ec-springboot-II)  client gives this error:  

[EC Client] 2017/03/02 15:05:20 websocket: bad handshake
[EC Client] 2017/03/02 15:05:20 runtime error: invalid memory address or nil pointer dereference

and gateway log shows:
[EC Debug] 2017/03/02 20:05:20 http.Header=>map[Authorization:[Basic xxxxxxxx]]
[EC Debug] 2017/03/02 20:05:20 int=>200
[EC Gateway] 2017/03/02 20:05:20 group validation failed. verify the agent ids are within the same group.

Not sure what I missed but I need some reference or help to achieve DB connection.

**Comment by palokam** [comment]
Perrin, will get in touch with you -- @plake06

**Comment by chiacchang** [comment]
User experience-relate question.
