### ISSUE TITLE
How to create server/client mode in Windows OS?

### ISSUE THREAD

**Issue by dgt009** [Enterprise-connect/ec-sdk#24]
As mentioned in this [four-way connectivity](https://github.com/Enterprise-connect/ec-sdk/wiki/Four-way-Connectivity)  (server mode)
how can we run ecagent_darwin_sys in windows OS ?? it isn't an executable file.  
![image](https://cloud.githubusercontent.com/assets/9281512/23554896/303eda9c-0027-11e7-9198-bdb0e5eb5529.png)

**Comment by chiacchang** [comment]
@dgt009 use ecagent_windows_sys.exe
