### ISSUE TITLE
EC gateway not coming up

### ISSUE THREAD

**Issue by kameshbrao** [Enterprise-connect/ec-sdk#25]
Hi,

I was trying to setup the EC gateway under the below CF login url. The listed plan to create the gateway is Beta and the OnewayTLS plan is not available yet. So when I use the Beta plan, the EC gateway service instance doesn't come up. Can you please let us know when would the OnewayTLS plan available for use or is there a fix for the Beta plan instances to comeup?

CF Login: **https://api.system.asv-pr.ice.predix.io**

Rgds,
Kamesh Rao

**Comment by palokam** [comment]
It is a known issue - Select and basic are not in sync with the plans

We will be fixing this on Wednesday 3/8/2017) evening

**Comment by palokam** [comment]
Issue resolved since we moved the plans into Select
