### ISSUE TITLE
Client Pool Management on Gateway

### ISSUE THREAD

**Issue by plake06** [Enterprise-connect/ec-sdk#33]
#Is it possible that in the scenario that gateway either loses connection the the server for whatever reason that all client request be either rejected or exception handled. Reason being is that the client pool will build because the gateway has no connect to the server and could cause unforeseen issues.

**Comment by chiacchang** [comment]
in client pool, suggesting 50 concurrent client requests to match the 50 superconns limitation. Work in progress.

**Comment by palokam** [comment]
sure - That will be fine to limit to 50 - we would not want to pile up more than 50 connections from client before we kill them as super-connection(s) is not available

**Comment by palokam** [comment]
fixed @plake06 @chiacchang
