### ISSUE TITLE
Run EC-Service outside of GE CF

### ISSUE THREAD

**Issue by zubairov** [Enterprise-connect/ec-sdk#34]
Can we run EC-Service outside of GE CF Cloud?

**Comment by chiacchang** [comment]
@zubairov the agent is supporting different platforms. Cloud Foundry containers run Linux64. Please refer to the supporting instruction/os in the README. https://github.com/Enterprise-connect/ec-sdk.

**Comment by zubairov** [comment]
Thanks. What about the *Service* (not agent)?

**Comment by chiacchang** [comment]
The managed service is currently available in CF, but can also be available to customisations outside of CF with a separate digital-signed certificate issued by the team.
