### ISSUE TITLE
Doc fixing - missing required params for server mode 

### ISSUE THREAD

**Issue by indaco** [Enterprise-connect/ec-sdk#37]
Filename: **README_ecagent.md**

Section: _Example usage in Server mode_

```shellscript
$\>./ecagent_darwin -aid 191001 -hst wss://ec-chia-app-7.run.aws-usw02-pr.ice.predix.io \
-rht localhost -rpt 5432 -cid <id> -csc <secret> \
-oa2 https://helo-a69c-4cc5-83bd-459aa307a307.predix-uaa.run.aws-usw02-pr.ice.predix.io/oauth/token \
-dur 300 -mod server
```

should be

```shellscript
$\>./ecagent_<your_os>_sys -aid 191001 -hst wss://ec-chia-app-7.run.aws-usw02-pr.ice.predix.io \
-rht localhost -rpt 5432 -cid <id> -csc <secret> \
-oa2 https://helo-a69c-4cc5-83bd-459aa307a307.predix-uaa.run.aws-usw02-pr.ice.predix.io/oauth/token \
-dur 300 -mod server -zon <ec_zoneId> -sst <ec_service_url>
```

to include `-zon` and `-sst` required params.

**Comment by palokam** [comment]
Yes, you are correct - we have to fix it - thanks for bringing to our attention

**Comment by palokam** [comment]
@plake06, did we fix the documentation for the additional flags for server?

**Comment by indaco** [comment]
You should also consider to fix the ecagent script name to include `_sys` as suggested with my previous comment.

It should be `$\>./ecagent_darwin_sys` and not `$\>./ecagent_darwin`

**Comment by palokam** [comment]
@indaco, sure we will

**Comment by chiacchang** [comment]
Close the issue since the associated repo had been deprecated and subject to removal.
