### ISSUE TITLE
Invalid memory address - Superconnection failing

### ISSUE THREAD

**Issue by madhu3984** [Enterprise-connect/ec-sdk#38]
Hi Team, we tried to scale down the gateway to 0 and after that we see Invalid memory address errors in the EC server component logs and EC server is not retrying for super connection.

how to reproduce:?

Step 1: cf scale -i 0 <<<appname>>>
Step 2: cf scale -i 2 <<<appname>>>
Step 3: verify the invalid memory address in the server logs
Step 4: check the Gateway health for super connection
Step 5: Do cf scale -i 3 <<<appname>>>
Step 6: you will see a successful super connection for instance 3 but not for other instances

**Comment by chiacchang** [comment]
See candidate release https://github.com/Enterprise-connect/ec-sdk/releases/tag/v1.3.2-candidate
