### ISSUE TITLE
Service failing with OutOfMemory

### ISSUE THREAD

**Issue by madhu3984** [Enterprise-connect/ec-sdk#39]
Hi Team,

We are seeing our EC service failing frequently with OOM and from the service logs, it is observed that for each call, we are doing token validation.

Hopefully by limiting the token validation should address EC Service crash happening due to OOM.

**Comment by chiacchang** [comment]
See candidate release. https://github.com/Enterprise-connect/ec-sdk/releases/tag/v1.3.2-candidate

**Comment by chiacchang** [comment]
Service-relate.
