### ISSUE TITLE
 - Deploy EC Service issue

### ISSUE THREAD

**Issue by chiacchang** [Enterprise-connect/ec-sdk#4]
When deploy EC Service through CF CS, the service stuck with "Creating in Progress".

**Comment by chiacchang** [comment]
When EC Service received create request, the service will try to clone a parental application and re-deploy the application for the usage. The clone/deploy progress takes up to 3 minutes and depend on the system's stability, the service will require longer/lesser time to complete it. We're in progress of improving the usage experience and will keep users updated.

**Comment by chiacchang** [comment]
This'll need an update in the EC service broker in CF.

**Comment by chiacchang** [comment]
decreased the memory usage to 64mb for EC service. Org clean up.

**Comment by palokam** [comment]
no longer an issue since we moved to the Service and gateway seperated
