### ISSUE TITLE
Agent Health API Enhancement

### ISSUE THREAD

**Issue by plake06** [Enterprise-connect/ec-sdk#40]
# **Server**

- Add Gateway Host URL
        Adding the Host URL to the health check API will allow me as a user to know if I am connected to the gateway and if I have a super connection to that gateway. 

- Add Connection Duration to Gateway Host
    Adding the current Super Connection duration to the Gateway will allow me as a user to know how stable my super connection has been to the Gateway.

- Add Aid of Server
    Adding the current server ID will allow me as a user another check to ensure that the correct server is up and running and speaking to the correct gateway.

# **Gateway**

- Add Connections Made
    Adding a running total of connections made will give me as a user a depiction of the grand total of session made

- Add Super Connection IP
   Adding the super connection IP addressing will allow me as a user to know the source of my super connection.

- Add last update Super connecting Ping
  Adding the last update ping will give me as a user a timeframe as to when the gateway last communicated with the server. 

- Add Connection Duration to Server
    Adding the current Super Connection duration to the Gateway will allow me as a user to know how stable my super connection has been to the server.

**Comment by chiacchang** [comment]
in planning.

**Comment by chiacchang** [comment]
Feature added in the beta release. Refer to the beta release note for detail.

**Comment by chiacchang** [comment]
- gateway:
            1. add num of conn since launch.
            2. Add the remote ip in the superconn pool
            3. add the last pong time in the superconn pool
            4. add conn time (created time) in the superconn pool.
            5. agent rev.
            6. IP/PID

- server:
            1. agent rev.
            2. agent id#
            3. gateway url
            4. superconn list (cf header included)
            5. IP/PID

- client:
            1. IP/PID
            2. agent id#
            3. agent rev.

**Comment by ayasuda2003** [comment]
Close the issue. Health HTTP Endpoint has since improved.
