### ISSUE TITLE
Server logging bug

### ISSUE THREAD

**Issue by plake06** [Enterprise-connect/ec-sdk#47]
The EC Agent while in server mode has a bug that has a default of verbose logging. The flag "dbg" is what is suppose to enable this verbose logging, however in the server mode this verbose logging show regardless of the presence of the flag. This has been tested in versions 199 and 202 of the hokkaido agent.

**Comment by palokam** [comment]
Once the fix tested @ayasuda2003 - please close this.

**Comment by ayasuda2003** [comment]
In release. https://github.com/Enterprise-connect/ec-x-sdk/releases/tag/v1.hokkaido.203
