### ISSUE TITLE
 - When operate EC as client/server in Windows, the connection didn't get established

### ISSUE THREAD

**Issue by chiacchang** [Enterprise-connect/ec-sdk#5]
The EC Server/Client mode does not receive a session id from the gateway as to acknowledge the connection. In investigation.

**Comment by palokam** [comment]
Please change the manifest.yml command parameter - 

**Before**
command:  ./ec_cf_script.sh
**After**
command:  _bash_ ./ec_cf_script.sh

**Comment by chiacchang** [comment]
Pending to verify.

**Comment by chiacchang** [comment]
Issue does not persist. tested in v1.64.
