### ISSUE TITLE
Enhancement: Reduce Agent modes for high speed data transfers

### ISSUE THREAD

**Issue by palokam** [Enterprise-connect/ec-sdk#51]
1) Eliminate the need(Fuse) for running 2 different apps for EC Gateway and EC Server when ingesting the data into Predix Cloud 

2) Eliminate the need to running the EC client and EC Gateway(Fuse)  when reaching back to on-premise network

This will eliminate half the network hops thus improve the performance.

**Comment by ayasuda2003** [comment]
In release. https://github.com/Enterprise-connect/ec-x-sdk/releases/tag/v1.hokkaido.203
