### ISSUE TITLE
Proxy issue with -dur flag

### ISSUE THREAD

**Issue by palokam** [Enterprise-connect/ec-sdk#7]
When -dur is used UAA or oauth provider is not able resolve the host, because it is using the host proxy settings instead of -pxy value. - Server running on corporate networks

**Temporary work around**
export http_proxy=your_http_proxy
export https_proxy=your_http_proxy
./ecagent_linux and the rest of the  flags

**Comment by chiacchang** [comment]
Agent update in progress.

**Comment by chiacchang** [comment]
bug fixed. please reopen if the issue persist. https://github.com/Enterprise-connect/ec-sdk/blob/master/README_ecagent.md
