### ISSUE TITLE
Add proper logging while closing the socket on [EC SERVER] logs

### ISSUE THREAD

**Issue by palokam** [Enterprise-connect/ec-sdk#9]
[EC Server] 2016/12/28 17:28:54 net.TCPConn closed while reading from the resource.
 [EC Server] 2016/12/28 17:28:54 net.TCPConn reached EOF from the io.read.

Please add sessionID and BindID# along with the close message. The will complete the picture of the open and close for sockets for communication.

**Comment by chiacchang** [comment]
Available in the feature release.

**Comment by chiacchang** [comment]
Close since the -dbg flag is introduced. https://github.com/Enterprise-connect/ec-sdk/blob/master/README_ecagent.md
